# Generated by fusen: do not edit by hand

# test_that("add_postcode_vars works properly and show error if needed", {
#   expect_true(add_postcode_vars(1:12) == 6.5)
#   expect_error(add_postcode_vars("text"))
# })
